### ISSUE TITLE
Need to consolidate liquidity

### ISSUE THREAD

**Issue by GiverofMemory** [adnjoo/smartcheese#3]
marketcap.cash requires liquidity to be 0.5 BCH at any swap that you want listed on the site.  So I reccomend you consolidate liquidity to one of your current swaps so you can get relisted on marketcap.cash

**Comment by adnjoo** [comment]
Hi I've added 0.5 BCH liquidity on Benswap
<img width="397" alt="liquidity" src="https://user-images.githubusercontent.com/22807629/149574093-7ad047c6-bfc8-468f-881a-a6a619a49549.png">
